# general
seed: 42
workers: 8

# train options
batch_size: 64  #DEFAULT 82
image_size: 224
start_epoch: 0
epochs: 1000
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / ImageNet-dogs / D0-40 / DTD47 / STL_10 /

# model options
feature_dim: 128
model_path: "save/ImageNet-10"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
